### ISSUE TITLE
How to debug

### ISSUE THREAD

**Issue by Immortalin** [kbrw/node_erlastic#4]
Hi! I am able to connect to the JS program but I am having timeout errors. How should I debug this? I put log functions in each of the callbacks to ensure that the JS program has received the GenServer message but to no avail.

**Comment by awetzel** [comment]
Hello, timeout error is when the `done` callback (4th parameter) is not called, since any exception can from another javascript event, there is no simple way in JS to catch all exception.
Fortunatly, you can use "Domain" node js errors to handle all exceptions : see for instance usage in 
`reaxt` : https://github.com/awetzel/reaxt/blob/master/priv/commonjs_reaxt/react_server.js#L56-L80

**Comment by awetzel** [comment]
sorry to answer late, I've just seen the notification with you closing the issue

**Comment by Immortalin** [comment]
@awetzel I managed to solve the problem, turned out that the `console.log` statement in my JavaScript code is buffered and thus interfering with erlang reading from stdout or something along that line.

**Comment by Immortalin** [comment]
@awetzel thanks for your help!

**Comment by Immortalin** [comment]
@awetzel is it possible for the server callback to be stateless? For some reason the term[] array is retaining state after callback has ended.
